version: '3.7'

services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./lab:/home/jovyan
    network_mode: "host"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - CHOWN_HOME=yes